;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Abilities.Attacks.BowAttack",DevComment="")
+GameplayTagList=(Tag="Abilities.Attacks.MeleeAttack.WeaponBash",DevComment="")
+GameplayTagList=(Tag="Abilities.ContextualAnim",DevComment="")
+GameplayTagList=(Tag="Abilities.Cover",DevComment="")
+GameplayTagList=(Tag="Abilities.MoveTo",DevComment="")
+GameplayTagList=(Tag="Camera.FirstPersonCameraWantsFollowHeadBone",DevComment="")
+GameplayTagList=(Tag="Foley",DevComment="")
+GameplayTagList=(Tag="Foley.Event",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Handplant",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Jump",DevComment="")
+GameplayTagList=(Tag="Foley.Event.LadderRung",DevComment="")
+GameplayTagList=(Tag="Foley.Event.LadderRung.Foot",DevComment="")
+GameplayTagList=(Tag="Foley.Event.LadderRung.Hand",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Land",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Run",DevComment="")
+GameplayTagList=(Tag="Foley.Event.RunBackwds",DevComment="")
+GameplayTagList=(Tag="Foley.Event.RunStrafe",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Scuff",DevComment="")
+GameplayTagList=(Tag="Foley.Event.ScuffPivot",DevComment="")
+GameplayTagList=(Tag="Foley.Event.ScuffWall",DevComment="")
+GameplayTagList=(Tag="Foley.Event.SwimSplash",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Tumble",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Walk",DevComment="")
+GameplayTagList=(Tag="Foley.Event.WalkBackwds",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Water.BigSplash",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Water.SmallSplash",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.Invisible",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.Invulnerable",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.Poisoned",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.Vigour",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ContextualAnim",DevComment="")
+GameplayTagList=(Tag="GameplayCue.TakeDamage",DevComment="")
+GameplayTagList=(Tag="GameplayCue.TakeDamage.Blocked",DevComment="")
+GameplayTagList=(Tag="GameplayCue.TakeDamage.Stumble",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.Execution",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.Fire",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.Fire.Melee",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.Fire.Execution",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.Fire.NoImpact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.Fire.NoImpact.Offhand",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.Fire.Offhand",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.Fire.UnarmedHit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.FireNoImpact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.FireNoImpact.Offhand",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.UnarmedImpact",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.Attack.Activate",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.Attack.Activate.Left",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.Attack.Activate.Mainhand",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.Attack.Activate.Offhand",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.Attack.Activate.UnarmedLeft",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.Attack.Bow.GrabbedArrow",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.Attack.Deactivate",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.Attack.Deactivate.Offhand",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.Attack.FinishAttack",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.Attack.HitTarget",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.KilledEnemy",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.Mounts.OnJackedFinished",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.NotifyHolster",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.WantsEndInteract.Carjacked",DevComment="")
+GameplayTagList=(Tag="MotionMatching",DevComment="")
+GameplayTagList=(Tag="MotionMatching.Default",DevComment="")
+GameplayTagList=(Tag="MotionMatching.Idle",DevComment="")
+GameplayTagList=(Tag="MotionMatching.Loops",DevComment="")
+GameplayTagList=(Tag="MotionMatching.Pivots",DevComment="")
+GameplayTagList=(Tag="MotionMatching.Starts",DevComment="")
+GameplayTagList=(Tag="MotionMatching.Stops",DevComment="")
+GameplayTagList=(Tag="Narrative.Anim.OverrideLayer.Ragdoll",DevComment="")
+GameplayTagList=(Tag="Narrative.Anim.OverrideLayer.Climbing.Ladder",DevComment="")
+GameplayTagList=(Tag="Narrative.AnimSets.Stumble.Forward",DevComment="")
+GameplayTagList=(Tag="Narrative.Anim.AnimSets.Flinch.Block",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Config.Sections.Eyes",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Config.Sections.Feet",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Config.Sections.General",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Config.Sections.Head",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Config.Sections.Legs",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Config.Sections.Torso",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Forms.HasanMale",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Forms.Horse",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Pages.Face.Sections.FaceShape",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Pages.Face.Sections.Hair",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Pages.Feet",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Pages.Feet.Sections.Footwear",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Pages.General",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Pages.General.Sections.GeneralInfo",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Pages.Legs.Sections.Legs",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Pages.Legs.Sections.Pants",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Pages.Torso.Sections.Tops",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Scalars.Age",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Scalars.Eyes.ColorA",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Scalars.Eyes.ColorB",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Scalars.Eyes.PupilSize",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Scalars.Weight",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Vectors.EyeColor",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Vectors.HairColor",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Vectors.Legs.PrimaryColor",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Vectors.Legs.SecondaryColor",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Vectors.Shoes.PrimaryColor",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Vectors.Shoes.SecondaryColor",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Vectors.Torso.PrimaryColor",DevComment="")
+GameplayTagList=(Tag="Narrative.CharacterCreator.Vectors.Torso.SecondaryColor",DevComment="")
+GameplayTagList=(Tag="Narrative.Damage.Types.Poison",DevComment="")
+GameplayTagList=(Tag="Narrative.Equipment.Slot.Grenade.Primary",DevComment="")
+GameplayTagList=(Tag="Narrative.Equipment.Slot.Mesh.Vest",DevComment="")
+GameplayTagList=(Tag="Narrative.Factions.Police",DevComment="")
+GameplayTagList=(Tag="Narrative.Input.Ability1",DevComment="5 Q - Generic ability bound to ability1 slot")
+GameplayTagList=(Tag="Narrative.Input.Ability2",DevComment="6 E - Generic ability bound to ability2 slot")
+GameplayTagList=(Tag="Narrative.Input.Ability3",DevComment="7 F - Generic ability bound to ability3 slot")
+GameplayTagList=(Tag="Narrative.Input.AltAttack",DevComment="4 RMB - Generic ability bound to alt attack slot (aim for firearms, block for melee, etc)")
+GameplayTagList=(Tag="Narrative.Input.Attack",DevComment="3 LMB - Generic attack ability bound to attack slot")
+GameplayTagList=(Tag="Narrative.Input.Attack.Heavy",DevComment="")
+GameplayTagList=(Tag="Narrative.Input.Cancel",DevComment="Cancel action for abilities")
+GameplayTagList=(Tag="Narrative.Input.Confirm",DevComment="Confirm action for abilities")
+GameplayTagList=(Tag="Narrative.Input.Cover",DevComment="")
+GameplayTagList=(Tag="Narrative.Input.Crouch",DevComment="L-Ctrl - Crouch")
+GameplayTagList=(Tag="Narrative.Input.Jump",DevComment="Space bar - Jumps")
+GameplayTagList=(Tag="Narrative.Input.None",DevComment="None - no input defined")
+GameplayTagList=(Tag="Narrative.Input.Reload",DevComment="8 R - reloads if our weapon supports")
+GameplayTagList=(Tag="Narrative.Input.Sprint",DevComment="Left shift - sprint")
+GameplayTagList=(Tag="Narrative.Input.Throw",DevComment="G - Throwable attack")
+GameplayTagList=(Tag="Narrative.InteractData.WantsInstantExit",DevComment="")
+GameplayTagList=(Tag="Narrative.POIs.BanditCamp",DevComment="")
+GameplayTagList=(Tag="Narrative.POIs.BanditTrainingArea",DevComment="")
+GameplayTagList=(Tag="Narrative.POIs.Forest.MagicArea",DevComment="")
+GameplayTagList=(Tag="Narrative.POIs.Forest.MeleeArea",DevComment="")
+GameplayTagList=(Tag="Narrative.POIs.GlenorchyWindmills",DevComment="")
+GameplayTagList=(Tag="Narrative.POIs.GreatPond",DevComment="")
+GameplayTagList=(Tag="Narrative.POIs.HeroesCamp",DevComment="")
+GameplayTagList=(Tag="Narrative.POIs.Market",DevComment="")
+GameplayTagList=(Tag="Narrative.POIs.ResidentialArea",DevComment="")
+GameplayTagList=(Tag="Narrative.POIs.WoodcuttersGuild",DevComment="")
+GameplayTagList=(Tag="Narrative.State.InCutscene",DevComment="")
+GameplayTagList=(Tag="Narrative.State.InCutscene.LockedMovement",DevComment="")
+GameplayTagList=(Tag="Narrative.State.InCutscene.NoCameraCuts",DevComment="")
+GameplayTagList=(Tag="Narrative.State.NPC.DisableLookAtNearbyChar",DevComment="")
+GameplayTagList=(Tag="Narrative.State.PreviewingPlayer",DevComment="")
+GameplayTagList=(Tag="Narrative.State.Stumbling",DevComment="added when GE_Stumble is active")
+GameplayTagList=(Tag="Narrative.State.Weapon.Bow.Drawing",DevComment="")
+GameplayTagList=(Tag="Narrative.State.Weapon.Equipped.Shield",DevComment="")
+GameplayTagList=(Tag="Narrative.TaggedDialogue.AimedAt",DevComment="")
+GameplayTagList=(Tag="Narrative.TaggedDialogue.Attack",DevComment="")
+GameplayTagList=(Tag="Narrative.TaggedDialogue.Carjacked",DevComment="")
+GameplayTagList=(Tag="Narrative.TaggedDialogue.Flee",DevComment="")
+GameplayTagList=(Tag="SetByCaller.Armor",DevComment="")
+GameplayTagList=(Tag="SetByCaller.AttackRating",DevComment="")
+GameplayTagList=(Tag="SetByCaller.Heal",DevComment="")
+GameplayTagList=(Tag="SetByCaller.Health",DevComment="")
+GameplayTagList=(Tag="SetByCaller.Stamina",DevComment="")
+GameplayTagList=(Tag="SetByCaller.StealthRating",DevComment="")
+GameplayTagList=(Tag="Sov.Ability.NPC.DominionHound.ChargeCooldown",DevComment="")
+GameplayTagList=(Tag="Sov.Ability.NPC.DominionHound.PounceCooldown",DevComment="")
