// Copyright Narrative Tools 2025.

#pragma once

#include "NativeGameplayTags.h"

NARRATIVEARSENAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MUSIC_AMBIENT)
NARRATIVEARSENAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MUSIC_COMBAT)
//NARRATIVEARSENAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MUSIC_PAUSE)
//NARRATIVEARSENAL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_MUSIC_LOADING)