// Copyright Fallen Signal Studios. All Rights Reserved.
#pragma once
#include "CoreMinimal.h"
PROJECTVELKORRAN_API DECLARE_LOG_CATEGORY_EXTERN(LogSovAbility, Log, All);
PROJECTVELKORRAN_API DECLARE_LOG_CATEGORY_EXTERN(LogSovCombat, Log, All);
PROJECTVELKORRAN_API DECLARE_LOG_CATEGORY_EXTERN(LogSovAI, Log, All);
PROJECTVELKORRAN_API DECLARE_LOG_CATEGORY_EXTERN(LogSovEncounter, Log, All);
PROJECTVELKORRAN_API DECLARE_LOG_CATEGORY_EXTERN(LogSovNarrative, Log, All);
PROJECTVELKORRAN_API DECLARE_LOG_CATEGORY_EXTERN(LogSovMission, Log, All);
PROJECTVELKORRAN_API DECLARE_LOG_CATEGORY_EXTERN(LogSovSave, Log, All);
PROJECTVELKORRAN_API DECLARE_LOG_CATEGORY_EXTERN(LogSovWorld, Log, All);
PROJECTVELKORRAN_API DECLARE_LOG_CATEGORY_EXTERN(LogSovUI, Log, All);
PROJECTVELKORRAN_API DECLARE_LOG_CATEGORY_EXTERN(LogSovCinematic, Log, All);
PROJECTVELKORRAN_API DECLARE_LOG_CATEGORY_EXTERN(LogSovPerformance, Log, All);
